<script lang="ts">
	import './descriptor-test.css';
	import chromiumLogo from '#lib/assets/browsers/chromium.svg';
	import firefoxLogo from '#lib/assets/browsers/firefox.svg';
	import safariLogo from '#lib/assets/browsers/safari.svg';
	import webkitLogo from '#lib/assets/browsers/webkit.svg';
	// The join of results/automated.json (generated by `pnpm test`) and
	// results/manual.json (hand-edited real-device results), by cell id — see
	// compat-results.ts. PLAYWRIGHT_VERSIONS is this repo's pinned Playwright,
	// queried via `browser.version()` rather than assumed from its release number.
	import {
		PLAYWRIGHT_VERSIONS,
		result,
		type RealSafari,
		type Verdict
	} from '#lib/fonts/compat-results';

	// Editorial verdict on the TECHNIQUE, distinct from the pass/fail Verdict
	// data above — "is this a bug" (Verdict) vs "should you use this" (Category).
	// A row can be all-true in Verdict and still be Legacy (safe but superseded)
	// or Ingredient (correct but not a complete recipe on its own). Six buckets,
	// not the four the matrix's own status-* colours use, because "should you
	// use this" has cases the pass/fail spectrum can't express: a row can be a
	// dead end nobody would choose (Diagnostic) or a historical pattern that
	// still works but isn't what fonts.css ships (Legacy) — neither is "broken."
	type Category = 'recommended' | 'incomplete' | 'avoid' | 'legacy' | 'ingredient' | 'diagnostic';
	const CATEGORY: Record<Category, { label: string; icon: string }> = {
		recommended: { label: 'Recommended', icon: '✓' },
		incomplete: { label: 'Incomplete', icon: '⚠' },
		avoid: { label: 'Avoid', icon: '✕' },
		legacy: { label: 'Legacy', icon: '○' },
		ingredient: { label: 'Ingredient', icon: '⚙' },
		diagnostic: { label: 'Diagnostic', icon: 'ℹ' }
	};

	// Techniques for slanting Cairo, which has no italic masters. Judged by eye:
	// slnt barely changes advance widths (Cairo's 'I' moves 248 -> 249 units per
	// 1000), so no width measurement can detect slant. The upright control sits
	// beside each row precisely so a failure looks like "nothing happened".
	//
	// `chromium`/`firefox`/`webkit` are MEASURED, from slant.browser.test.ts,
	// which runs these exact techniques through real engines on every
	// `pnpm test` — docs/compat.md has the numbers. `webkit` is Playwright's
	// bundled build, which is NOT real Safari and is certainly not old real
	// Safari — that gap is the entire reason `safariOld`/`safariNew` exist as
	// separate, real-device fields.
	//
	// Each is `null` (not device-tested — rendered as a neutral `?`, never a
	// tick or cross) or a real claim carrying its device/version label: this
	// exact CSS was checked on that exact device, by hand (results/manual.json),
	// and is rendered as a solid tick/cross. Always read the row's own `expect`
	// text before trusting either.
	//
	// Two real devices back the hand-tested results:
	//   - "iPhone XR" / "Safari 18.7" — old, the device the original backslant
	//     bug was reported on.
	//   - "macOS desktop" / "Safari 27.0" (build 20625.1.29.18.28) — new.
	const SLANT_TESTS: {
		id: string;
		title: string;
		css: string;
		expect: string;
		klass: string;
		browsers: Verdict;
		category: Category;
	}[] = [
		{
			id: 'oblique-range-combo',
			category: 'recommended',
			title:
				"font-style: oblique 11deg + font-variation-settings: 'slnt' -11 — RECOMMENDED, what fonts.css ships",
			css: "font-style: oblique 11deg; font-variation-settings: 'slnt' -11  (face declares: font-style: oblique -11deg 11deg)",
			expect:
				'Two SEPARATE problems, one pairing that fixes both. Problem one: bare font-style: ' +
				'oblique (no angle) implies a default that falls outside a declared range, tripping a ' +
				'Chromium/WebKit synthesis bug (see the trap rows below) — fixed by stating the EXACT ' +
				'angle, 11deg, instead. Problem two: real Safari 18.7 performs NO automatic font-style ' +
				'-> slnt mapping at all, for any font-style value, exact angle or not — a completely ' +
				'different, device-level gap that stating the angle correctly does nothing for. This ' +
				'pairing fixes both at once: the exact angle sidesteps problem one, and the explicit ' +
				'slnt value sidesteps problem two by not depending on the mapping succeeding at all — ' +
				"an element's own font-variation-settings always wins over whatever font-style-matching " +
				'would or would not do. Confirmed correct in Chromium, Firefox, Playwright WebKit, and ' +
				'on real Safari 18.7 AND 27.0 — including against a family carrying the normal-style ' +
				'face fonts.css always ships alongside this one, not just an isolated face with no ' +
				'sibling (slant.browser.test.ts). The slnt half is provably safe to delete later, once ' +
				'the mapping is trusted on every version in the field — not yet.',
			klass: 'm-oblique-range-combo',
			browsers: result('oblique-range-combo')
		},
		{
			id: 'oblique-range-angle',
			category: 'incomplete',
			title:
				'font-style: oblique 11deg ALONE against the TRUE range — correct, but not sufficient by itself',
			css: 'font-style: oblique 11deg  (face declares: font-style: oblique -11deg 11deg)',
			expect:
				'This is what you get if you drop the slnt half of the recommended row above — do not. ' +
				"Unlike the bare keyword, 11deg IS within this face's declared range, so there is " +
				'nothing for Chromium or WebKit to fall back to synthesis for — resolves via the axis ' +
				'alone, correctly, in every automated engine, and confirmed on real Safari 27.0. But ' +
				'confirmed BROKEN on real Safari 18.7: that device performs no automatic font-style -> ' +
				'slnt mapping at all, exact angle or not, the same gap every other font-style-only row ' +
				'in this matrix hits. Getting the angle right solves the synthesis trap; it does not ' +
				'solve the device-support gap — those are two different problems (see the recommended ' +
				'row above).',
			klass: 'm-oblique-range-angle',
			browsers: result('oblique-range-angle')
		},
		{
			id: 'italic-vs-range',
			category: 'avoid',
			title: 'font-style: italic against the TRUE -11deg..11deg range — broken, differently',
			css: 'font-style: italic; font-synthesis: weight style  (face declares: font-style: oblique -11deg 11deg)',
			expect:
				"Per spec, italic's angle is not 14deg like bare oblique's — it is explicitly " +
				'"unspecified" (CSS Fonts 4) — so this is a DIFFERENT gap from the row below, not the ' +
				'same one restated: whatever angle an engine picks for italic, it is not guaranteed to ' +
				"fall inside this face's declared -11..11 bounds either, and it doesn't here. Broken in " +
				'the same two engines as the row below, but by a DIFFERENT amount: Chromium leans ' +
				'~0.44, the same double-stack shape as bare oblique (axis correctly set to -11, plus a ' +
				"synthetic skew on top). WebKit leans ~0.25 this time, not ~0.44 — that's tan(14deg), a " +
				'PURE synthetic skew with NO axis contribution at all, a third, genuinely different ' +
				'failure mode. Measured, not assumed to match the row below just because both are "the ' +
				'trap." Only Firefox is correct. Confirmed broken on real Safari, both 18.7 and 27.0. ' +
				"font-synthesis is forced back to weight+style here — this site's own font-synthesis: " +
				'weight would otherwise neutralise the trap by accident.',
			klass: 'm-italic-range',
			browsers: result('italic-vs-range')
		},
		{
			id: 'oblique-explicit',
			category: 'avoid',
			title: 'font-style: oblique (BARE) against the TRUE range — still the trap, avoid',
			css: 'font-style: oblique; font-synthesis: weight style  (face declares: font-style: oblique -11deg 11deg)',
			expect:
				"-11deg..11deg is not an arbitrary or mismatched range — it's Cairo's actual fvar slnt " +
				'bounds (min -11, default 0, max 11), and it is what fonts.css now ships. The trap is ' +
				'specifically the BARE keyword: CSS Fonts 4 says lack of an angle implies 14deg, which ' +
				"is OUTSIDE this face's declared bounds, so Chromium and WebKit fall back to synthesis " +
				'to reach 14deg on top of the (correctly matched) axis — Chromium leans roughly twice ' +
				'as far, WebKit prefers synthesis over the axis outright and lands near the same ' +
				'overshoot. Only Firefox is correct. This is exactly why the recommended pattern above ' +
				'is not optional: writing bare font-style: oblique against the face fonts.css actually ' +
				'ships, without the exact angle, hits this trap. font-synthesis is forced back to ' +
				"weight+style here — this site's own font-synthesis: weight would otherwise neutralise " +
				'the trap by accident. Confirmed broken on real Safari, both 18.7 and 27.0.',
			klass: 'm-oblique-range',
			browsers: result('oblique-explicit')
		},
		{
			id: 'oblique-angle',
			category: 'avoid',
			title:
				'font-style: oblique 11deg against a family with BOTH normal and BARE oblique — historical hazard',
			css: 'font-style: oblique 11deg  (family declares font-style: normal AND a BARE font-style: oblique, no range — no longer what fonts.css ships)',
			expect:
				"CSS Fonts 4: OpenType's slnt axis is positive counter-clockwise, CSS's oblique angle " +
				"is positive clockwise — so stating the angle here SHOULD target 'slnt' -11 via " +
				'font-style-matching alone. It does, in Firefox. It does NOT in Chromium or WebKit: ' +
				'both pick the wrong face and render upright — not a partial lean, no lean at all. This ' +
				'is specifically about a BARE oblique descriptor competing ambiguously with a normal ' +
				'sibling for an angled request — fonts.css no longer ships a face shaped like this (see ' +
				'the recommended row above), but the hazard stays real if you ever hand-roll a face ' +
				'this way yourself: a bare oblique descriptor gives the matching algorithm no bounds to ' +
				'prefer it unambiguously. A RANGED oblique descriptor does not have this problem (see ' +
				"'oblique 11deg ALONE' above) — confirmed broken on real Safari, both 18.7 and 27.0.",
			klass: 'm-oblique-angle',
			browsers: result('oblique-angle')
		},
		{
			id: 'recommended',
			category: 'legacy',
			title: "font-style: oblique + font-variation-settings: 'slnt' -11 — historical, still valid",
			css: "font-style: oblique; font-variation-settings: 'slnt' -11  (face declares: font-style: oblique, no range)",
			expect:
				'What fonts.css recommended before the migration to a declared range (see the RECOMMENDED ' +
				'row above) — still correct today, against a face with no declared range, and still a ' +
				'valid choice if you ever ship or consume a face shaped this way. font-style: oblique ' +
				'is the semantically correct way to ask for this (CSS Fonts 4 font-style-matching); the ' +
				'explicit slnt value is what makes it deterministic regardless of whether a given engine ' +
				"performs that mapping at all — an element's own explicit font-variation-settings always " +
				'wins over any automatic mapping, so whichever half an engine honours, the other covers ' +
				'it. Confirmed by hand on both real Safari 18.7 and 27.0.',
			klass: 'm-recommended',
			browsers: result('recommended')
		},
		{
			id: 'fvs-use-site',
			category: 'ingredient',
			title: "font-variation-settings: 'slnt' -11 alone — the deterministic ingredient",
			css: "font-variation-settings: 'slnt' -11",
			expect:
				'Leans forward. This sets the axis directly — no automatic font-style mapping involved, ' +
				'so nothing to disagree about across engines, versions, or which face is in play, and ' +
				'immune to the ancestor-pin hazard below. It is one half of the recommended pattern ' +
				'above, not a replacement for font-style: pairing it with font-style keeps the semantic ' +
				'layer without giving up determinism. Confirmed by hand on both real Safari 18.7 and ' +
				'27.0, not just reasoned from the mechanism.',
			klass: 'm-usesite',
			browsers: result('fvs-use-site')
		},
		{
			id: 'oblique-bare',
			category: 'legacy',
			title: 'font-style: oblique alone (bare, no italic), against a range-free face — historical',
			css: 'font-style: oblique  (face declares: font-style: oblique, no range)',
			expect:
				'Per the CSS Fonts 4 font-style-matching algorithm, this is an exact match against the ' +
				"face's own font-style: oblique descriptor — no italic-to-oblique fallback step. Leans " +
				'~11deg in Chromium, current WebKit and Firefox. On real devices this is confirmed ' +
				'version-dependent, not a permanent Safari limitation: broken on Safari 18.7 (iPhone ' +
				'XR), fixed by Safari 27.0 (macOS desktop) — the exact version this changed in is ' +
				'unknown, only these two endpoints are confirmed. Pair with explicit slnt for ' +
				'determinism on anything between those two — this is exactly the same lesson as the ' +
				'RECOMMENDED row at the top, just against a range-free face rather than the one ' +
				'fonts.css now actually ships.',
			klass: 'm-oblique-bare',
			browsers: result('oblique-bare')
		},
		{
			id: 'oblique-range',
			category: 'legacy',
			title: 'font-style: italic against a range-free bare `oblique` face — historical',
			css: 'font-style: italic  (face declares: font-style: oblique, no range)',
			expect:
				'Leans ~11deg in Chromium, current WebKit and Firefox — but confirmed UPRIGHT on real ' +
				'Safari 18.7 (iPhone XR): it does not perform this automatic font-style -> slnt mapping ' +
				'at all, even with no ancestor pin in the way. Confirmed fixed on Safari 27.0, matching ' +
				'the bare-oblique row above — this time measured, not the earlier guess that it was ' +
				'"probably fixed alongside it." Playwright’s WebKit is a different, newer build and ' +
				'reproduces neither gap — this is a real engine divergence you can only catch by hand. ' +
				'font-style: italic is fine as a semantic hint; pair it with explicit slnt (or prefer ' +
				'bare oblique, one layer less indirect) for determinism.',
			klass: 'm-oblique',
			browsers: result('oblique-range')
		},
		{
			id: 'fvs-descriptor',
			category: 'diagnostic',
			title: 'HISTORICAL, DO NOT USE — font-variation-settings as an @font-face DESCRIPTOR',
			css: "@font-face { font-variation-settings: 'slnt' -11 }",
			expect:
				'Not a live recommendation — kept as a regression guard. The old hand-written font.css ' +
				'relied on this. Measured DEAD in WebKit — upright, no lean at all — so Cairo italic was ' +
				'silently broken in Safari all along, the whole time that file was live. Demoted out of ' +
				"the Quick matrix above: it's not a viable alternative worth comparing side by side with " +
				'the working techniques, just a documented reason not to reintroduce it. Not separately ' +
				'device-confirmed in isolation from the original backslant bug report; not re-tested here.',
			klass: 'm-descriptor',
			browsers: result('fvs-descriptor')
		},
		{
			id: 'synthesis',
			category: 'diagnostic',
			title: 'Faux-oblique synthesis on top of a real axis',
			css: "font-style: italic  +  font-variation-settings: 'slnt' -11",
			expect:
				'Should look the SAME as the recommended row above. If it leans noticeably further, the ' +
				'engine is synthesising a skew on top of the real axis — fix with font-synthesis: none.',
			klass: 'm-synthesis',
			browsers: result('synthesis')
		}
	];

	function find(id: string) {
		const t = SLANT_TESTS.find((x) => x.id === id);
		if (!t) throw new Error(`no SLANT_TESTS entry '${id}'`);
		return t.browsers;
	}

	// Mechanism-based, like fvs-use-site: an explicit same-element slnt value
	// always wins regardless of what the face's own font-style descriptor is
	// doing, so this is true independent of the descriptor being tested.
	// Measured against the ranged face specifically (slant.browser.test.ts),
	// and hand-checked on both real devices — but it has no detail section of
	// its own, hence a constant here rather than a find() reference.
	const EXPLICIT_SLNT_ANYWHERE: Verdict = result('fvs-anywhere-B');

	// Rows = what the @font-face declares. Columns = what's set at the use
	// site. Cells reference the detailed SLANT_TESTS entry below wherever one
	// exists, so there is exactly one source of truth per claim; `null` means
	// genuinely untested/not meaningful for that combination, not "assumed
	// fine" — left blank rather than guessed at.
	// Numbered 0-5, literal CSS rather than prose, so each row states exactly
	// what's being asked for at the use site — no paraphrasing to double-check
	// against the css shown lower on the page.
	const MATRIX_COLS = [
		{ id: 'none', num: 0, lines: ['(nothing set)'] },
		{ id: 'italic', num: 1, lines: ['font-style: italic;'] },
		{ id: 'oblique', num: 2, lines: ['font-style: oblique;'] },
		{ id: 'obliqueAngle', num: 3, lines: ['font-style: oblique 11deg;'] },
		{ id: 'slnt', num: 4, lines: ["font-variation-settings: 'slnt' -11;"] },
		{
			id: 'combo',
			num: 5,
			lines: ['font-style: oblique 11deg;', "font-variation-settings: 'slnt' -11;"]
		}
	] as const;

	// The use-site CSS each column actually applies, for the overlap-diff
	// glyph. 'none' is deliberately empty — that's the point of that column.
	// 'combo' matches row 5's literal label (oblique 11deg + slnt) exactly —
	// this is what fonts.css now ships and recommends. The historical row
	// below overrides the font-style half back to bare via its own cell's
	// extraCss, since bare oblique + slnt was the old recommendation there.
	const MATRIX_COL_CSS: Record<(typeof MATRIX_COLS)[number]['id'], string> = {
		none: '',
		italic: 'font-style: italic;',
		oblique: 'font-style: oblique;',
		obliqueAngle: 'font-style: oblique 11deg;',
		slnt: "font-variation-settings: 'slnt' -11;",
		combo: "font-style: oblique 11deg; font-variation-settings: 'slnt' -11;"
	};

	// `control`: the "(nothing set)" column — nothing requests a slant, so it is
	// trivially upright everywhere. Shown as a glyph and a note, never measured
	// or listed in results/*.json.
	type MatrixCell = { verdict: Verdict; extraCss?: string } | { control: true } | null;

	const MATRIX_ROWS: {
		id: string;
		code: string;
		note: string;
		family: string;
		cells: Record<(typeof MATRIX_COLS)[number]['id'], MatrixCell>;
	}[] = [
		{
			id: 'oblique-range-face',
			code: '@font-face { font-style: oblique -11deg 11deg; }',
			note: "The font's real slnt bounds — shipped by fonts.css",
			// The REAL 'Cairo' family — since font-src/css.py now declares this
			// exact range, this row's overlap glyphs render against the same
			// file this site (and every consumer) actually loads.
			family: 'Cairo',
			cells: {
				none: { control: true },
				// This site's own app.css sets font-synthesis: weight globally,
				// which neutralises the trap by accident (docs/compat.md, "the
				// oblique-range trap is neutralised by font-synthesis: weight").
				// Without restating font-synthesis: weight style here too, both
				// cells below would render as a false pass, contradicting their
				// own verdict badges. Matches the css field on the
				// 'italic-vs-range'/'oblique-explicit' SLANT_TESTS entries exactly.
				italic: { verdict: find('italic-vs-range'), extraCss: 'font-synthesis: weight style;' },
				oblique: { verdict: find('oblique-explicit'), extraCss: 'font-synthesis: weight style;' },
				// Passes without needing the font-synthesis override the row
				// above needs — matches 'oblique-range-angle' exactly, measured
				// with and without style synthesis allowed (slant.browser.test.ts),
				// and against a family carrying the normal-style sibling face too.
				obliqueAngle: { verdict: find('oblique-range-angle') },
				// Mechanism-based, like EXPLICIT_SLNT_ANYWHERE below: setting the
				// axis directly bypasses font-style-matching entirely, so it can't
				// care which @font-face block is active. Same reasoning, not a
				// separately-exercised browser test.
				slnt: { verdict: EXPLICIT_SLNT_ANYWHERE },
				combo: { verdict: find('oblique-range-combo') }
			}
		},
		{
			id: 'oblique-bare-face',
			code: '@font-face { font-style: oblique; }',
			note: "The font's style only — historical, no longer shipped",
			// An isolated test family (descriptor-test.css), NOT the real
			// 'Cairo' — the real family moved to the ranged descriptor above.
			// Kept as a live comparison point, and as the "if you hand-roll a
			// face this way yourself" hazard reference for oblique-angle below.
			family: 'CairoBareTest',
			cells: {
				none: { control: true },
				italic: { verdict: find('oblique-range') },
				oblique: { verdict: find('oblique-bare') },
				obliqueAngle: { verdict: find('oblique-angle') },
				slnt: { verdict: find('fvs-use-site') },
				// Overrides column 5's base (oblique 11deg + slnt) back to bare
				// oblique + slnt — the historical recommendation for THIS face,
				// matching the 'recommended' SLANT_TESTS entry's css field exactly.
				combo: { verdict: find('recommended'), extraCss: 'font-style: oblique;' }
			}
		}
	];

	function matrixStatus(
		cell: MatrixCell
	): 'control' | 'pass' | 'version-dependent' | 'broken' | null {
		if (cell === null) return null;
		if ('control' in cell) return 'control';
		const v = cell.verdict;
		const automatedPass = v.chromium && v.firefox && v.webkit;
		const realFail = (v.safariOld && !v.safariOld.pass) || (v.safariNew && !v.safariNew.pass);
		const realPassOrUnknown =
			(v.safariOld === null || v.safariOld.pass) && (v.safariNew === null || v.safariNew.pass);
		if (automatedPass && realPassOrUnknown) return 'pass';
		if (automatedPass && realFail) return 'version-dependent';
		return 'broken';
	}

	// These do change metrics, so the page checks them itself.
	let auto = $state<{ label: string; detail: string; pass: boolean }[]>([]);

	function measure(text: string, style: string) {
		const el = document.createElement('span');
		el.style.cssText = `position:absolute;visibility:hidden;white-space:pre;font-size:200px;font-family:Cairo;${style}`;
		el.textContent = text;
		document.body.appendChild(el);
		const width = el.getBoundingClientRect().width;
		el.remove();
		return width;
	}

	$effect(() => {
		void document.fonts.ready.then(() => {
			const kernOn = measure('AVAWAY', 'font-kerning:normal');
			const kernOff = measure('AVAWAY', 'font-kerning:none');
			const upright = measure('Hamburgefonstiv', '');
			const slanted = measure('Hamburgefonstiv', "font-variation-settings:'slnt' -11");

			auto = [
				{
					label: 'GPOS kerning is active',
					detail: `AVAWAY: ${kernOn.toFixed(1)}px kerned vs ${kernOff.toFixed(1)}px unkerned`,
					pass: Math.abs(kernOn - kernOff) > 0.5
				},
				{
					label: 'slnt does NOT meaningfully change advance width',
					detail: `${upright.toFixed(1)}px upright vs ${slanted.toFixed(1)}px slanted — which is why the rows above need eyes, not measurement`,
					pass: Math.abs(upright - slanted) < upright * 0.01
				}
			];
		});
	});
</script>

<h1>Testing Cairo's oblique italic across browsers</h1>
<p class="lede">
	Cairo has no italic masters — its italic is entirely the <code>slnt</code> variable axis, not a
	separate face. Asking a browser to slant it (<code>font-style: italic</code>,
	<code>oblique</code>, an explicit axis value, or some combination) can resolve very differently
	depending on how you ask and which engine is rendering it. This page tests every viable technique,
	in real engines and on real devices, to work out which ones are safe to rely on and which ones are
	traps — and to justify the pattern <a href="/use">/use</a> tells consumers to write.
</p>
<p class="lede">
	Every technique below is already asserted in Chromium, WebKit and Firefox by
	<code>src/lib/fonts/slant.browser.test.ts</code>, which measures rendered shear on every
	<code>pnpm test</code>; results are in <code>docs/compat.md</code>. This page exists for the one
	thing that cannot automate: <b>real Safari</b>, which Playwright's WebKit is not.
</p>

<div class="tldr">
	<h2>TL;DR</h2>
	<p class="tldr-lead">
		<b>Summary:</b>
		<b
			>ship <code>font-style: oblique 11deg</code> + explicit
			<code>font-variation-settings: 'slnt' -11</code></b
		>
		(the recommended row below) — this is what <code>fonts.css</code> now ships, confirmed correct
		on every tested case: Chromium, Firefox, Playwright's WebKit, and real Safari
		<b>18.7 AND 27.0</b>, including against the normal-style sibling face <code>fonts.css</code> always
		ships alongside this one. It fixes two SEPARATE problems at once — see below.
	</p>
	<ul>
		<li>
			<b>Two separate problems, easy to conflate:</b> (1) a Chromium/WebKit synthesis bug, triggered
			when a use-site keyword's angle falls outside a declared <code>@font-face</code> range; (2)
			real Safari 18.7 performing <b>no</b> automatic <code>font-style</code> →
			<code>slnt</code> mapping at all, for any keyword, exact angle or not — a device/version gap,
			not an engine bug. Stating the exact angle fixes problem 1. Pairing it with an explicit
			<code>slnt</code> fixes problem 2. You need both.
		</li>
		<li>
			<code>font-style: oblique &lt;angle&gt;</code> is the CSS Fonts 4
			<a href="https://drafts.csswg.org/css-fonts-4/#font-style-matching">spec's own mechanism</a>
			for matching a specific point inside a declared <code>slnt</code> range — not a workaround.
			Bare <code>oblique</code> (no angle) falls back to a stated default of <b>14deg</b>;
			<code>italic</code>'s angle is spec-defined as <b>unspecified</b>. Neither is guaranteed to
			fall inside this face's declared <b>-11deg..11deg</b> bounds, and neither does — that's problem
			1 above. State the exact angle instead.
		</li>
		<li>
			The exact angle alone is still not enough — confirmed <b>BROKEN</b> on real Safari 18.7
			(that's problem 2). Pair it with <code>font-variation-settings: 'slnt' -11</code>: an
			element's own explicit value directly sets the axis, regardless of whether font-style-matching
			succeeds on a given engine or version. Confirmed correct on both real Safari 18.7 and 27.0.
		</li>
		<li>
			This required checking the <b>tested versions</b>, not "every version" — only two real Safari
			data points exist (18.7 and 27.0); the exact version the gap closed in between them is
			unknown.
		</li>
		<li>
			A family carrying both a normal and a <b>bare</b> oblique face together is a separate,
			historical hazard: Chromium and WebKit pick the wrong face for an angled request and render
			upright. This is no longer what <code>fonts.css</code> ships — the recommended row's ranged face
			does not have this ambiguity — but it's a real trap if you ever hand-roll a face this way yourself.
			See "historical hazard" below.
		</li>
		<li>
			Change weight with the <code>font-weight</code> <b>property</b>
			(<code>font-weight: 700</code>), not by stating <code>'wght'</code> through
			<code>font-variation-settings</code>. Measured: a lone <code>'wght'</code> value alone doesn't
			break <code>slnt</code> either, in a flat, unpinned case — but the property can never interact
			with <code>slnt</code> at all, in any component tree, so it carries none of the font-variation-settings-replaces-not-merges
			risk (the "second real-device finding" below) by construction.
		</li>
	</ul>
	<p class="tldr-note">
		Independently corroborated: Safari has lagged on this exact CSS Fonts 4 behaviour since at least
		2020 — see <a href="https://arrowtype.github.io/vf-slnt-test/index.html"
			>ArrowType's vf-slnt-test</a
		>, a community test suite (last run November 2022) that found Safari passing almost nothing
		except <code>font-variation-settings</code> itself against variable fonts, across three years of
		retests. Its recommendation to fall back to <code>transform: skew()</code> is for fonts
		<i>missing</i> the requested axis value entirely — a different, spec-acknowledged ambiguous case
		— not this one: Cairo has a real <code>slnt</code> axis and <code>font-style: oblique</code>
		matches it directly.
	</p>
</div>

{#snippet badge(logo: string, label: string, pass: boolean | null)}
	<li
		class="b-badge"
		class:pass={pass === true}
		class:fail={pass === false}
		class:unknown={pass === null}
		title="{label}: {pass === null ? 'untested on a real device' : pass ? 'pass' : 'fail'}"
	>
		<img class="logo" src={logo} alt={label} />
	</li>
{/snippet}

{#snippet realSafari(r: RealSafari, fallbackLabel: string)}
	{#if r === null}
		{@render badge(safariLogo, fallbackLabel, null)}
	{:else}
		{@render badge(safariLogo, r.version, r.pass)}
	{/if}
{/snippet}

{#snippet verdictBadges(v: Verdict)}
	<!-- Ordered Firefox (passes almost everything, the reference point) ->
	     Chromium (the next-most-often-buggy automated engine) -> WebKit
	     (Playwright's programmatic proxy for Safari) -> Safari, new (the
	     current real-device visual check) — then a visual separator before
	     Safari, old, which is real and important but a separate, historical
	     data point, not part of the "current" run. -->
	<ul class="verdicts">
		{@render badge(firefoxLogo, `Firefox ${PLAYWRIGHT_VERSIONS.firefox}`, v.firefox)}
		{@render badge(chromiumLogo, `Chromium ${PLAYWRIGHT_VERSIONS.chromium}`, v.chromium)}
		{@render badge(webkitLogo, `WebKit ${PLAYWRIGHT_VERSIONS.webkit} (Playwright)`, v.webkit)}
		{@render realSafari(v.safariNew, 'Safari (new)')}
		<li class="badge-sep" aria-hidden="true"></li>
		{@render realSafari(v.safariOld, 'Safari (old)')}
	</ul>
{/snippet}

{#snippet overlapGlyph(family: string, testCss: string)}
	<div class="overlap">
		<span
			class="ov-control"
			style="font-family: '{family}', var(--font-sans); font-variation-settings: 'slnt' -11;"
			>VIZChitra</span
		>
		<span class="ov-test" style="font-family: '{family}', var(--font-sans); {testCss}"
			>VIZChitra</span
		>
	</div>
{/snippet}

<h2>Quick matrix</h2>
<p class="hint">
	Rows are what the <code>@font-face</code> declares; columns are what's set at the use site. Each
	populated cell overlays two renderings of the same glyphs: <b class="ov-control-label">pink</b> is
	the always-correct control (<code>font-variation-settings: 'slnt' -11</code> directly, on the same
	family), <b class="ov-test-label">the other colour</b> is the technique being tested. Aligned, the
	two colours screen together into a pale blend — <b>visible pink is a failure</b>, not a subtle
	one. Blank cells are untested or not a meaningful combination for that face, not "assumed fine."
	Full detail — why each populated cell is what it is — is in "Slant techniques" below.
</p>
<div class="matrix-wrap">
	<!-- Transposed for reading ease: 5 use-site settings read better as rows
	     (a short vertical list) than as 5 columns needing horizontal scroll,
	     with the 3 @font-face variants across the top instead. The underlying
	     data (MATRIX_ROWS = face variants, MATRIX_COLS = use-site settings)
	     is unchanged; only the render order is swapped. -->
	<table class="matrix">
		<thead>
			<tr>
				<th></th>
				{#each MATRIX_ROWS as face (face.id)}
					<th><code>{face.code}</code><span class="col-note">{face.note}</span></th>
				{/each}
			</tr>
		</thead>
		<tbody>
			{#each MATRIX_COLS as useSite (useSite.id)}
				<tr>
					<th scope="row">
						<span class="row-num">{useSite.num}.</span>
						<code>
							{#each useSite.lines as line, i (i)}
								{line}{#if i < useSite.lines.length - 1}<br />{/if}
							{/each}
						</code>
					</th>
					{#each MATRIX_ROWS as face (face.id)}
						{@const cell = face.cells[useSite.id]}
						{@const status = matrixStatus(cell)}
						<td class="status-{status ?? 'blank'}">
							{#if cell === null}
								<span class="blank-cell">—</span>
							{:else}
								{@render overlapGlyph(
									face.family,
									MATRIX_COL_CSS[useSite.id] + (cell.extraCss ?? '')
								)}
								{#if 'control' in cell}
									<p class="control-note">
										trivial — nothing here requests a slant, not a meaningful test
									</p>
								{:else}
									{@render verdictBadges(cell.verdict)}
								{/if}
							{/if}
						</td>
					{/each}
				</tr>
			{/each}
		</tbody>
	</table>
</div>

<ul class="legend">
	<li><span class="b-badge pass"></span> pass</li>
	<li><span class="b-badge fail"></span> fail</li>
	<li><span class="b-badge unknown"></span> untested on a real device</li>
	<li class="legend-note">Hover a badge for the exact device/version.</li>
</ul>
<ul class="legend legend-versions">
	<li>
		<img class="logo" src={firefoxLogo} alt="Firefox" /> Firefox {PLAYWRIGHT_VERSIONS.firefox}
	</li>
	<li>
		<img class="logo" src={chromiumLogo} alt="Chromium" /> Chromium {PLAYWRIGHT_VERSIONS.chromium}
	</li>
	<li>
		<img class="logo" src={webkitLogo} alt="WebKit" /> WebKit {PLAYWRIGHT_VERSIONS.webkit} (Playwright)
	</li>
	<li><img class="logo" src={safariLogo} alt="Safari (new)" /> Safari 27.0 (macOS desktop)</li>
	<li class="badge-sep" aria-hidden="true"></li>
	<li><img class="logo" src={safariLogo} alt="Safari (old)" /> Safari 18.7 (iPhone XR)</li>
</ul>

<h2>The iOS Safari backslant</h2>
<p class="hint">
	The original bug, and the reason this page exists. Reported on <b>Safari 18.7, iPhone XR</b>:
	Cairo renders leaning <i>backwards</i> when <code>slnt</code> is left to the font's default. Desktop
	engines look fine, so this only shows up on an actual old device.
</p>
<p class="hint">
	The cause is that <code>font-variation-settings</code> <b>replaces</b> the inherited value rather
	than merging with it — so declaring only <code>'wght'</code> silently discards any upright reset.
	The <code>@font-face</code> descriptor cannot save you here: it is measurably inert in WebKit.
</p>

<div class="rows">
	<section>
		<h3>Left: axis unpinned — Right: <code>'slnt' 0</code> stated</h3>
		<code class="css">font-variation-settings: 'wght' 600 &nbsp;vs&nbsp; 'wght' 600, 'slnt' 0</code>
		<div class="specimen">
			<div class="half">
				<span class="tag">unpinned — backslants on old iOS</span>
				<div class="sample m-unpinned">VIZCHITRA</div>
			</div>
			<div class="half">
				<span class="tag">pinned — correct everywhere</span>
				<div class="sample m-pinned">VIZCHITRA</div>
			</div>
		</div>
		<p class="expect">
			These must look identical. If the left one leans back, this device has the bug. The fix is
			component-level, not a global reset: any rule that states <code>'wght'</code> via
			<code>font-variation-settings</code> must also state <code>'slnt'</code>
			(<code>src/lib/fonts/axis-pinning.test.ts</code> enforces this for this repo's own code). An
			earlier version of this fix instead pinned <code>'slnt' 0</code> on <code>html</code> in
			<code>app.css</code> — that broke <code>font-style: italic</code> everywhere, on every engine,
			because an ancestor's explicit <code>slnt</code> blocks the browser's automatic mapping from
			<code>font-style</code> onto the axis. The "Hazard demo" section further down re-checks that on
			this device.
		</p>
	</section>
</div>

<h2>Slant techniques — judge by eye</h2>
<p class="hint">
	Each row shows the technique on the left and an untouched upright control on the right. <b
		>A failure looks like the two halves matching.</b
	>
</p>

<div class="rows">
	{#each SLANT_TESTS as t (t.id)}
		<section class="cat-{t.category}">
			<h3>
				<span class="cat-badge cat-{t.category}"
					>{CATEGORY[t.category].icon} {CATEGORY[t.category].label}</span
				>
				{t.title}
			</h3>
			<code class="css">{t.css}</code>
			<div class="specimen">
				<div class="half">
					<span class="tag">technique</span>
					<div class="sample {t.klass}">VIZChitra</div>
				</div>
				<div class="half">
					<span class="tag">upright control</span>
					<div class="sample">VIZChitra</div>
				</div>
			</div>
			<p class="expect">{t.expect}</p>
			{@render verdictBadges(t.browsers)}
		</section>
	{/each}
</div>

<h2>Self-checking</h2>
<p class="hint">These change measurable metrics, so the page tests them itself.</p>
<ul class="auto">
	{#each auto as row (row.label)}
		<li class:pass={row.pass}>
			<b>{row.pass ? 'PASS' : 'FAIL'}</b>
			<span>{row.label}</span>
			<em>{row.detail}</em>
		</li>
	{:else}
		<li><span>Measuring…</span></li>
	{/each}
</ul>

<h2>Hazard demo: an ancestor pin kills italic (deliberately broken — not our CSS)</h2>
<p class="hint">
	The middle half is expected to look upright, unlike the left — this is the exact bug an earlier
	version of the iOS fix reintroduced by pinning <code>slnt</code> on <code>html</code>. If
	<code>app.css</code> ever adds such a pin back, this middle half is how it would show up. Both use
	a bare specimen with no <code>font-variation-settings</code> of their own — not
	<code>.sample .m-oblique</code>, which now states <code>font-variation-settings: normal</code> on
	itself and so is deliberately immune to any ancestor, this one included.
	<br /><br />
	<b>On real Safari 18.7 (iPhone XR), the left half shows upright too</b> — not because of the
	ancestor pin, but because that engine does not perform the automatic
	<code>font-style</code> → <code>slnt</code> mapping at all, pin or no pin (fixed by Safari 27.0 —
	see the TL;DR above). The left and middle halves become visually indistinguishable there, which is
	itself the case for pairing <code>font-style</code> with an explicit value rather than relying on
	the mapping alone: you cannot tell "blocked by an ancestor" apart from "this version never
	supported it" by eye. The right half sidesteps the whole question — it sets
	<code>font-variation-settings: 'slnt' -11</code> directly, so there is no automatic mapping to be
	blocked or unsupported, and it leans correctly under the very same pinned ancestor, on every
	engine and version including old real Safari. This is the deterministic half of the recommended
	pattern above, not a reason to drop <code>font-style</code> entirely.
</p>
<div class="rows">
	<section>
		<h3>
			Left: italic, no ancestor pin. Middle: same, under a pinned ancestor — stays upright. Right:
			explicit slnt, under the SAME pinned ancestor — leans correctly regardless
		</h3>
		<code class="css"
			>font-style: italic &nbsp;vs&nbsp; (ancestor: font-variation-settings: 'slnt' 0) font-style:
			italic &nbsp;vs&nbsp; (same ancestor) font-variation-settings: 'slnt' -11</code
		>
		<div class="specimen aligned">
			<div class="half">
				<span class="tag">no ancestor pin<br />correct only where italic is supported</span>
				<div class="hazard-specimen">VIZCHITRA</div>
			</div>
			<div class="half slnt-pinned-ancestor">
				<span class="tag">nested under a slnt-pinned ancestor<br />broken on purpose</span>
				<div class="hazard-specimen">VIZCHITRA</div>
			</div>
			<div class="half slnt-pinned-ancestor">
				<span class="tag">same pinned ancestor<br />explicit slnt stays immune</span>
				<div class="hazard-specimen-explicit">VIZCHITRA</div>
			</div>
		</div>
	</section>
</div>

<style>
	.lede,
	.hint {
		color: var(--text-muted);
		font-size: 0.9rem;
		max-width: 48rem;
	}

	.hint {
		font-size: 0.82rem;
	}

	.tldr {
		max-width: 48rem;
		margin: 1rem 0 2rem;
		padding: 0.9rem 1.1rem;
		border: 1px solid var(--border);
		border-left: 3px solid var(--accent);
		border-radius: var(--radius);
		background: var(--surface-hover);
	}

	.tldr h2 {
		margin: 0 0 0.5rem;
		padding-bottom: 0;
		border-bottom: none;
		font-size: 1rem;
	}

	.tldr-lead {
		margin: 0 0 0.8rem;
		padding-bottom: 0.7rem;
		border-bottom: 1px dashed var(--border);
		font-size: 0.9rem;
	}

	.tldr ul {
		margin: 0;
		padding-left: 1.2rem;
		font-size: 0.88rem;
	}

	.tldr li {
		margin: 0.4rem 0;
	}

	.tldr-note {
		margin: 0.9rem 0 0;
		padding-top: 0.7rem;
		border-top: 1px dashed var(--border);
		font-size: 0.8rem;
		color: var(--text-muted);
	}

	/* The overlap-diff glyph: two renderings of the same text, stacked exactly
	   on top of each other. isolation:isolate scopes mix-blend-mode to just
	   these two spans so it doesn't affect anything else on the page. Where
	   the technique under test (cyan) renders identically to the always-
	   correct control (pink), screen-blending the two produces a pale colour
	   with no pink visible on its own — a slant that's missing, wrong, or
	   shaped differently shows up as an uncovered pink fringe. */
	.overlap {
		position: relative;
		isolation: isolate;
		height: 2.6rem;
		font-size: 2rem;
		line-height: 1;
		margin-bottom: 0.5rem;
	}

	.overlap span {
		position: absolute;
		top: 0;
		left: 0;
		white-space: nowrap;
		mix-blend-mode: screen;
	}

	.ov-control,
	.ov-control-label {
		color: #f472b6;
	}

	.ov-test,
	.ov-test-label {
		color: #22d3ee;
	}

	.matrix-wrap {
		overflow-x: auto;
	}

	table.matrix {
		display: table;
		min-width: 100%;
	}

	table.matrix th,
	table.matrix td {
		vertical-align: top;
	}

	table.matrix thead th code {
		display: block;
		font-size: 0.78rem;
		background: none;
		padding: 0;
		white-space: normal;
	}

	table.matrix .col-note {
		display: block;
		margin-top: 0.25rem;
		font-size: 0.75rem;
		font-weight: normal;
		font-style: italic;
		color: var(--text-muted);
	}

	table.matrix .row-num {
		font-weight: bold;
		color: var(--text-muted);
	}

	table.matrix tbody th code {
		font-size: 0.78rem;
		background: none;
		padding: 0;
	}

	table.matrix td {
		min-width: 12.5rem;
		border-left-width: 3px;
	}

	td.status-pass {
		border-left-color: #4ade80;
	}

	td.status-version-dependent {
		border-left-color: #fbbf24;
	}

	td.status-broken {
		border-left-color: #f87171;
	}

	td.status-control {
		border-left-color: var(--border);
	}

	td.status-blank {
		border-left-color: var(--border);
	}

	.blank-cell {
		color: var(--text-muted);
	}

	.control-note {
		margin: 0;
		font-size: 0.72rem;
		font-style: italic;
		color: var(--text-muted);
	}

	table.matrix .verdicts {
		flex-wrap: nowrap;
		gap: 0.3rem;
	}

	.legend {
		list-style: none;
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: 0.4rem 1.2rem;
		padding: 0.75rem 0 1.5rem;
		margin: 0;
		font-size: 0.78rem;
		color: var(--text-muted);
	}

	.legend li {
		display: inline-flex;
		align-items: center;
		gap: 0.4rem;
	}

	.legend .b-badge {
		width: 1.2rem;
		height: 1.2rem;
		border-width: 2px;
	}

	.legend-note {
		font-style: italic;
	}

	.legend-versions {
		padding-top: 0;
	}

	.rows {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	section {
		border: 1px solid var(--border);
		border-radius: var(--radius);
		padding: 0.9rem 1rem 1rem;
	}

	/* Category colours reuse the matrix's own pass/version-dependent/broken
	   palette where the meaning lines up (recommended=pass green,
	   incomplete=version-dependent amber, avoid=broken red), so the same
	   colour means the same thing whether you're looking at a matrix cell or
	   a technique row. Legacy/ingredient/diagnostic have no matrix
	   equivalent — they're about whether to USE a technique, not whether it
	   passes — so they get their own hues, chosen to stay visually distinct
	   from the pass/fail spectrum and from each other. */
	section.cat-recommended {
		border-left: 3px solid #4ade80;
	}
	section.cat-incomplete {
		border-left: 3px solid #fbbf24;
	}
	section.cat-avoid {
		border-left: 3px solid #f87171;
	}
	section.cat-legacy {
		border-left: 3px solid #94a3b8;
	}
	section.cat-ingredient {
		border-left: 3px solid #60a5fa;
	}
	section.cat-diagnostic {
		border-left: 3px solid #c084fc;
	}

	h3 {
		margin: 0 0 0.3rem;
		font-size: 0.95rem;
		display: flex;
		flex-wrap: wrap;
		align-items: baseline;
		gap: 0.5rem;
	}

	.cat-badge {
		display: inline-flex;
		align-items: center;
		gap: 0.25rem;
		font-size: 0.68rem;
		font-weight: bold;
		letter-spacing: 0.03em;
		text-transform: uppercase;
		padding: 0.15rem 0.5rem;
		border-radius: 1rem;
		white-space: nowrap;
		color: var(--bg);
	}

	.cat-badge.cat-recommended {
		background: #4ade80;
	}
	.cat-badge.cat-incomplete {
		background: #fbbf24;
	}
	.cat-badge.cat-avoid {
		background: #f87171;
	}
	.cat-badge.cat-legacy {
		background: #94a3b8;
	}
	.cat-badge.cat-ingredient {
		background: #60a5fa;
	}
	.cat-badge.cat-diagnostic {
		background: #c084fc;
	}

	.css {
		display: block;
		font-size: 0.75rem;
		color: var(--text-muted);
		background: none;
		padding: 0;
		margin-bottom: 0.6rem;
	}

	.specimen {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
		gap: 0.75rem;
	}

	.half {
		border: 1px dashed var(--border);
		border-radius: var(--radius);
		padding: 0.5rem 0.7rem;
		overflow: hidden;
	}

	/* Each half's label and specimen become two rows of the parent grid, so
	   the specimens line up however many lines each label wraps to. */
	.aligned .half {
		display: grid;
		grid-template-rows: subgrid;
		grid-row: span 2;
		row-gap: 0;
	}

	/* Reproduces the exact hazard: an ancestor stating 'slnt' explicitly. This
	   must never live in app.css — it is only here to prove, on this device,
	   that the pattern is still broken if anyone reintroduces it. */
	.slnt-pinned-ancestor {
		font-variation-settings: 'slnt' 0;
	}

	/* Deliberately bare — no font-variation-settings of its own, unlike
	   .sample. This isolates the ancestor's effect. .m-oblique (used in the
	   table below) states `font-variation-settings: normal` on itself and so
	   would stay correct here too, which is the whole reason it needed its
	   own class rather than reusing this one. */
	/* 'CairoBareTest' (historical, range-free face), not the real 'Cairo' —
	   the real family is now ranged, and italic against a RANGED face hits a
	   different bug (the trap rows above) with a different visual signature
	   (over/under-slanted, not upright), which would muddy this demo's one
	   point: an ancestor's explicit slnt blocks the automatic mapping,
	   nothing else. */
	.hazard-specimen {
		font-family: 'CairoBareTest', var(--font-sans);
		font-size: 2.6rem;
		line-height: 1.2;
		font-style: italic;
	}

	/* The recommended technique: sets the axis directly, so there is no
	   automatic font-style -> slnt mapping for an ancestor pin (or a real
	   Safari that never implemented the mapping at all) to interfere with. */
	.hazard-specimen-explicit {
		font-family: 'Cairo', var(--font-sans);
		font-size: 2.6rem;
		line-height: 1.2;
		font-variation-settings: 'slnt' -11;
	}

	.tag {
		display: block;
		font-size: 0.65rem;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--text-muted);
		margin-bottom: 0.2rem;
	}

	.sample {
		font-family: 'Cairo', var(--font-sans);
		font-size: 2.6rem;
		line-height: 1.2;
		/* 'slnt' 0 is stated, not omitted — see the backslant section above. */
		font-variation-settings:
			'wght' 600,
			'slnt' 0;
	}

	/* The iOS Safari backslant demo. Deliberately omits slnt, which is the bug. */
	.m-unpinned {
		font-variation-settings: 'wght' 600;
	}

	.m-pinned {
		font-variation-settings:
			'wght' 600,
			'slnt' 0;
	}

	.expect {
		margin: 0.6rem 0 0;
		font-size: 0.78rem;
		color: var(--text-muted);
	}

	.verdicts {
		list-style: none;
		display: flex;
		flex-wrap: wrap;
		gap: 0.4rem;
		padding: 0;
		margin: 0.6rem 0 0;
	}

	/* Separates the "current run" badges (Firefox/Chromium/WebKit/Safari-new)
	   from Safari-old — a real, important data point, but a separate,
	   historical one, not part of what you'd re-run today. */
	.badge-sep {
		width: 2px;
		align-self: stretch;
		background: var(--text-muted);
		opacity: 0.5;
		margin: 0 0.25rem;
		border-radius: 1px;
	}

	/* Circular logo badge with a coloured ring: green pass, red fail, grey
	   dashed for genuinely untested. Full detail (device, version) is in the
	   title tooltip, not repeated as text in every cell now that this is a
	   compact grid. */
	.b-badge {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 1.9rem;
		height: 1.9rem;
		padding: 0.2rem;
		border-radius: 50%;
		border: 2px solid #f87171;
		background: var(--surface-hover);
	}

	.b-badge.pass {
		border-color: #4ade80;
	}

	.b-badge.unknown {
		border-color: var(--border);
		border-style: dashed;
	}

	.logo {
		width: 1.15rem;
		height: 1.15rem;
		flex: none;
	}

	/* One technique per class, so nothing leaks between rows. */

	/* The RECOMMENDED pattern, what fonts.css now ships: font-style for
	   semantics, explicit slnt for determinism. The explicit value always
	   wins on the same element, so this measures correctly regardless of
	   whether a given engine performs the font-style -> slnt mapping at
	   all. Uses the real 'Cairo' family (inherited from .sample) — font-src/
	   css.py now declares this exact range, so this demo runs against the
	   same file every consumer loads, normal-style sibling included. */
	.m-oblique-range-combo {
		font-style: oblique 11deg;
		font-variation-settings:
			'wght' 600,
			'slnt' -11;
	}

	/* The recommended row's angle half alone, without the slnt half — kept
	   deliberately incomplete to demonstrate why both matter (real Safari
	   18.7 has no automatic mapping at all, exact angle or not). Real
	   'Cairo' family, same as above. */
	.m-oblique-range-angle {
		font-style: oblique 11deg;
		font-variation-settings: normal;
	}

	/* The bare-keyword trap, against the REAL shipped range. `normal`
	   releases .sample's 'slnt' 0 so the technique is actually exercised. */
	.m-italic-range {
		font-style: italic;
		font-variation-settings: normal;
		font-synthesis: weight style;
	}

	.m-oblique-range {
		font-style: oblique;
		font-variation-settings: normal;
		/* html sets font-synthesis: weight globally, which happens to
		   neutralise this exact trap (slant.browser.test.ts, "the
		   oblique-range trap is neutralised by font-synthesis: weight") —
		   forbidding synthesis removes the synthetic skew Chromium and
		   WebKit stack on top of the axis, leaving the correct angle. This
		   row needs to re-enable synthesis to demonstrate the danger a
		   consumer sees if they adopt bare font-style: oblique against the
		   ranged face WITHOUT also setting font-synthesis correctly, which
		   fonts.css cannot enforce for them. Getting there took three wrong
		   turns, each confirmed wrong with a real browser rather than
		   assumed. (1) `auto` is not a valid font-synthesis value, so the
		   browser silently drops it and does nothing. (2) `revert` is NOT
		   "ignore all author CSS" — font-synthesis is an inherited property,
		   and revert falls back to the INHERITED value when no lower-origin
		   rule exists, which is exactly html's `weight` again. (3) the full
		   initial value, `weight style small-caps position`, got the whole
		   declaration dropped by the dev server's CSS pipeline for
		   Chromium/WebKit specifically (confirmed via document.styleSheets
		   in each engine) — `position` is a newer Level 4 keyword, and
		   whatever browser-target logic strips unsupported values dropped
		   the entire shorthand rather than degrading it. `weight style` is
		   the original, universally-supported two-value form and survives
		   everywhere; we don't need small-caps/position for this demo
		   anyway. */
		font-synthesis: weight style;
	}

	/* Historical hazard: a family with a normal AND a BARE oblique face
	   together (no longer what fonts.css ships — see 'CairoBareTest',
	   descriptor-test.css). Chromium and WebKit pick the wrong face for an
	   explicit angle and stay upright; only Firefox honours it
	   (slant.browser.test.ts). Do not build a face shaped like this. */
	.m-oblique-angle {
		font-family: 'CairoBareTest', var(--font-sans);
		font-style: oblique 11deg;
		font-variation-settings: normal;
	}

	/* Historical pattern: font-style + explicit slnt against a range-free
	   face — still correct, no longer what fonts.css ships. */
	.m-recommended {
		font-family: 'CairoBareTest', var(--font-sans);
		font-style: oblique;
		font-variation-settings:
			'wght' 600,
			'slnt' -11;
	}

	.m-usesite {
		font-variation-settings:
			'wght' 600,
			'slnt' -11;
	}

	/* .sample states 'slnt' 0 on THIS SAME element (not an ancestor), and an
	   explicit same-element value beats font-style's automatic mapping even
	   more directly than an inherited one does. `normal` releases it — the
	   font-variation-settings initial value, meaning "no CSS-level override,
	   let font-style/the @font-face descriptor decide" — so the technique
	   below is actually being tested, not silently pinned upright regardless
	   of what it does. Historical: 'CairoBareTest', not the real (now
	   ranged) 'Cairo'. */
	.m-oblique {
		font-family: 'CairoBareTest', var(--font-sans);
		font-style: italic;
		font-variation-settings: normal;
	}

	.m-oblique-bare {
		font-family: 'CairoBareTest', var(--font-sans);
		font-style: oblique;
		font-variation-settings: normal;
	}

	.m-descriptor {
		/* Relies on the @font-face descriptor in the block below — which an
		   explicit CSS-level 'slnt' would override if left in place. */
		font-family: 'CairoDescriptorTest', var(--font-sans);
		font-variation-settings: normal;
	}

	.m-synthesis {
		font-style: italic;
		font-variation-settings:
			'wght' 600,
			'slnt' -11;
	}

	.auto {
		list-style: none;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 0.4rem;
	}

	.auto li {
		display: grid;
		grid-template-columns: 3.5rem 1fr;
		gap: 0.2rem 0.6rem;
		border: 1px solid var(--border);
		border-left: 3px solid #f87171;
		border-radius: var(--radius);
		padding: 0.5rem 0.7rem;
		font-size: 0.85rem;
	}

	.auto li.pass {
		border-left-color: #4ade80;
	}

	.auto b {
		font-size: 0.7rem;
		letter-spacing: 0.06em;
	}

	.auto em {
		grid-column: 2;
		font-style: normal;
		font-size: 0.75rem;
		color: var(--text-muted);
	}
</style>
