"""Generate fonts.css from the built subsets.

    uv run font-src/css.py

Generated, never hand-edited, so the @font-face blocks cannot drift from the
files that actually exist in static/fonts/v1/. Written to two places from one
source: src/lib/styles/fonts.css for this site's own `@import`, and
static/fonts/v1/fonts.css so external consumers have a stable, versioned URL
to <link> directly - see docs/plan.md 2.1.

Deliberately omits a synthetic Cairo italic. The old font.css declared one with
a `font-variation-settings: 'slnt' -11` @font-face DESCRIPTOR, which is the
weakest-supported corner of the spec. Until /compat records real Safari results,
callers set slant through font-variation-settings at the use site instead.
"""

import json
from pathlib import Path

from ranges import css_range

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "static" / "fonts" / "v1"
CSS_PATHS = [ROOT / "src" / "lib" / "styles" / "fonts.css", OUT_DIR / "fonts.css"]

# basename -> (css family, weight range, extra descriptors)
FACES = {
	"Cairo-Variable": ("Cairo", "200 1000", []),
	"IBMPlexSans-Variable": ("IBM Plex Sans", "100 700", ["font-stretch: 75% 100%;"]),
	"IBMPlexSans-Variable-Italic": ("IBM Plex Sans", "100 700", ["font-stretch: 75% 100%;"]),
	"FiraCode-Variable": ("Fira Code", "300 700", []),
}

# Cairo has no italic masters - its italic IS the slnt axis, so an italic face
# reuses the same files with a different style descriptor.
#
# The BARE `oblique` keyword, with no angle range. Measured in all three engines
# by src/lib/fonts/slant.browser.test.ts; do not "improve" this into a range:
#
#   font-style: oblique              -> 0.194 / 0.193 / 0.194   correct everywhere
#   font-style: oblique 0deg 11deg   -> 0.444 / 0.249 / 0.194   wrong in 2 of 3
#
# With a range, Chromium stacks a 14deg synthetic skew ON TOP of the real axis
# and WebKit ignores the axis and synthesises instead. Only Firefox gets it right.
CAIRO_ITALIC = "font-style: oblique;"

HEADER = """/* Generated by font-src/css.py - do not edit by hand.
   Run `uv run font-src/subset.py && uv run font-src/css.py` to regenerate.

   Sources are pinned in fonts.lock.json. Each family comes from a DIFFERENT
   upstream; see docs/plan.md.

   Fira Code's own family name is "Fira Code Light" and its wght axis defaults
   to 300, so anything using it must set an explicit font-weight or it renders
   Light. That is upstream's naming, not a packaging mistake here. */
"""


CAIRO_ITALIC_NOTE = """/* Cairo italic. The font has no italic masters - "italic" IS slnt -11 - so these
   reuse the upright files with an oblique style descriptor.

   The bare `oblique` keyword is deliberate and load-bearing. Verified in
   Chromium, WebKit and Firefox by src/lib/fonts/slant.browser.test.ts, which
   measures the actual rendered shear; results in docs/compat.md. Adding an angle
   range breaks it in two of three engines: Chromium stacks a synthetic skew on
   top of the real axis, WebKit drops the axis and synthesises instead.

   DO NOT rely on `font-style: italic` alone for correct rendering. Confirmed on
   a real iPhone XR (Safari 18.7): that engine does not perform the automatic
   font-style -> slnt mapping this descriptor enables AT ALL, pin or no pin -
   Playwright's WebKit is a different, newer build that does, which is why this
   didn't show up in the automated test suite. Set the axis directly instead:

       font-variation-settings: 'slnt' -11;

   at the use site, alongside font-style: italic if you like (harmless, purely
   semantic once the explicit value is present - it wins over any automatic
   mapping). See docs/compat.md, "The second real-device finding".

   The previous hand-written font.css used a `font-variation-settings: 'slnt' -11`
   @font-face DESCRIPTOR, which silently does nothing at all in WebKit/Safari. */"""


def face(family: str, sub: dict, weights: str, style: str, extra: list[str]) -> str:
	return "\n".join(
		[
			"@font-face {",
			f"\tfont-family: '{family}';",
			f"\tsrc: url('/fonts/v1/{sub['file']}') format('woff2');",
			f"\tfont-weight: {weights};",
			f"\t{style}",
			"\tfont-display: swap;",
			*(f"\t{e}" for e in extra),
			f"\tunicode-range: {css_range(sub['subset'])};",
			"}",
		]
	)


def main() -> int:
	manifest = json.loads((OUT_DIR / "manifest.json").read_text())
	blocks = [HEADER]

	for key, entries in manifest.items():
		blocks.append(f"\n/* --- {key} --- */")
		for entry in entries:
			family, weights, extra = FACES[entry["basename"]]
			for sub in entry["subsets"]:
				blocks.append(
					face(family, sub, weights, f"font-style: {entry['style']};", extra)
				)

			if entry["basename"] == "Cairo-Variable":
				blocks.append(CAIRO_ITALIC_NOTE)
				for sub in entry["subsets"]:
					blocks.append(face(family, sub, weights, CAIRO_ITALIC, extra))

	text = "\n\n".join(blocks) + "\n"
	for css in CSS_PATHS:
		css.parent.mkdir(parents=True, exist_ok=True)
		css.write_text(text)

	faces = sum(len(e["subsets"]) for v in manifest.values() for e in v)
	for css in CSS_PATHS:
		print(f"wrote {css.relative_to(ROOT)}  ({faces} @font-face blocks)")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
