"""Generate fonts.css from the built subsets.

    uv run font-src/css.py

Generated, never hand-edited, so the @font-face blocks cannot drift from the
files that actually exist in static/fonts/v1/. Written to two places from one
source: src/lib/styles/fonts.css for this site's own `@import`, and
static/fonts/v1/fonts.css so external consumers have a stable, versioned URL
to <link> directly - see docs/plan.md 2.1.

Deliberately omits a synthetic Cairo italic via @font-face DESCRIPTOR. The old
font.css declared one with `font-variation-settings: 'slnt' -11` as a
descriptor, which is measured dead in WebKit/Safari - see CAIRO_ITALIC_NOTE
below. Cairo's italic ships as a real @font-face declaring its true slnt
range instead; callers must still set the axis explicitly at the use site
(confirmed by real-device testing, not assumed - docs/manual.json, /compat).
"""

import json
from pathlib import Path

from ranges import css_range

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "static" / "fonts" / "v1"
CSS_PATHS = [ROOT / "src" / "lib" / "styles" / "fonts.css", OUT_DIR / "fonts.css"]

# basename -> (css family, weight range, extra descriptors)
FACES = {
	"Cairo-Variable": ("Cairo", "200 1000", []),
	"IBMPlexSans-Variable": ("IBM Plex Sans", "100 700", ["font-stretch: 75% 100%;"]),
	"IBMPlexSans-Variable-Italic": ("IBM Plex Sans", "100 700", ["font-stretch: 75% 100%;"]),
	"FiraCode-Variable": ("Fira Code", "300 700", []),
}

# Cairo has no italic masters - its italic IS the slnt axis, so this face
# reuses the upright files with an oblique style descriptor.
#
# Declares the font's TRUE slnt range (min -11, default 0, max 11) - not the
# bare `oblique` keyword this used to ship. That reversal is deliberate, and
# the two techniques are NOT interchangeable:
#
#   font-style: oblique               -> correct everywhere against a face
#                                         with no declared range, but this
#                                         face no longer has no range
#   font-style: oblique -11deg 11deg  -> breaks the BARE oblique keyword in
#                                         2 of 3 engines: CSS's implied
#                                         default of 14deg for "no angle
#                                         stated" falls OUTSIDE this range,
#                                         forcing a synthesis fallback on
#                                         top of the (correctly matched) axis
#
# The fix is a REQUIRED use-site pattern, not the face descriptor alone - see
# CAIRO_ITALIC_NOTE below and docs/use, "Cairo's italic." Measured in all
# three engines by src/lib/fonts/slant.browser.test.ts, including against a
# family carrying both this face and the normal-style face above together -
# the exact shape this file generates, not an isolated face with no sibling.
CAIRO_ITALIC = "font-style: oblique -11deg 11deg;"

HEADER = """/* Generated by font-src/css.py - do not edit by hand.
   Run `uv run font-src/subset.py && uv run font-src/css.py` to regenerate.

   Sources are pinned in fonts.lock.json. Each family comes from a DIFFERENT
   upstream; see docs/plan.md.

   Fira Code's own family name is "Fira Code Light" and its wght axis defaults
   to 300 internally - that is upstream's naming, not a packaging mistake here.
   It does NOT mean an unset font-weight renders Light: the @font-face block
   below declares font-weight as a 300..700 RANGE, so the CSS initial value
   (400, "normal") falls inside it and an unset weight resolves to 400, not
   the font's internal default. Measured in all three engines, bit-identical
   to an explicit font-weight: 400 - src/lib/fonts/fira-code.browser.test.ts.
   The risk would only be real if this range descriptor were dropped. */
"""


CAIRO_ITALIC_NOTE = """/* Cairo italic. The font has no italic masters - "italic" IS slnt -11 - so these
   reuse the upright files with an oblique style descriptor declaring the
   font's TRUE range (-11deg 11deg), not a bare keyword.

   REQUIRED use-site pattern - this is not optional, for two SEPARATE reasons:

       font-style: oblique 11deg;
       font-variation-settings: 'slnt' -11;

   1. The angle must be EXACT (11deg), not bare `font-style: oblique` or
      `italic`. CSS's implied default angle for "no angle stated" is 14deg
      (italic's is spec-unspecified, but measures the same in practice) -
      both fall OUTSIDE this face's declared bounds, so Chromium and WebKit
      fall back to synthesis on top of the axis, landing at roughly twice
      the correct shear. Only Firefox tolerates the bare/unspecified form
      against a ranged face. Verified in all three engines by
      src/lib/fonts/slant.browser.test.ts, including against a family
      carrying both this face and the normal-style face together - the
      shape this file actually generates, not an isolated face with no
      sibling.

   2. Even the exact angle alone is not deterministic across the field:
      confirmed on a real iPhone XR (Safari 18.7) that this engine performs
      NO automatic font-style -> slnt mapping at all, exact angle or not -
      Playwright's WebKit is a different, newer build that does, which is
      why this gap doesn't show up in the automated test suite. The
      explicit 'slnt' -11 covers that: an element's own font-variation-
      settings value always wins over whatever the automatic mapping would
      or wouldn't do, so the combo is correct regardless of which half a
      given engine honours. Confirmed by hand on real Safari 18.7 AND
      27.0 - see docs/manual.json and /compat.

   The bare `oblique` keyword this file used to ship remains correct too,
   against a face with no declared range - but requires no use-site angle
   discipline, which is exactly why it was the safer default until this
   migration. See docs/use, "Cairo's italic," for the full explanation.

   The previous hand-written font.css used a `font-variation-settings: 'slnt' -11`
   @font-face DESCRIPTOR, which silently does nothing at all in WebKit/Safari. */"""


def face(family: str, sub: dict, weights: str, style: str, extra: list[str]) -> str:
	return "\n".join(
		[
			"@font-face {",
			f"\tfont-family: '{family}';",
			f"\tsrc: url('/fonts/v1/{sub['file']}') format('woff2');",
			f"\tfont-weight: {weights};",
			f"\t{style}",
			"\tfont-display: swap;",
			*(f"\t{e}" for e in extra),
			f"\tunicode-range: {css_range(sub['subset'])};",
			"}",
		]
	)


def main() -> int:
	manifest = json.loads((OUT_DIR / "manifest.json").read_text())
	blocks = [HEADER]

	for key, entries in manifest.items():
		blocks.append(f"\n/* --- {key} --- */")
		for entry in entries:
			family, weights, extra = FACES[entry["basename"]]
			for sub in entry["subsets"]:
				blocks.append(
					face(family, sub, weights, f"font-style: {entry['style']};", extra)
				)

			if entry["basename"] == "Cairo-Variable":
				blocks.append(CAIRO_ITALIC_NOTE)
				for sub in entry["subsets"]:
					blocks.append(face(family, sub, weights, CAIRO_ITALIC, extra))

	text = "\n\n".join(blocks) + "\n"
	for css in CSS_PATHS:
		css.parent.mkdir(parents=True, exist_ok=True)
		css.write_text(text)

	faces = sum(len(e["subsets"]) for v in manifest.values() for e in v)
	for css in CSS_PATHS:
		print(f"wrote {css.relative_to(ROOT)}  ({faces} @font-face blocks)")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
